-- ============================================================================
-- 부엉이게임 파일럿 — 방(room) 멀티세션 재초기화 스크립트
-- Supabase SQL Editor 에 전체 붙여넣고 Run. public 스키마를 비우고 재생성합니다.
-- ⚠️ 기존 데이터가 있으면 모두 삭제됩니다.
--
-- 모델: 한 배포 + 한 DB 가 무제한 동시 "방"을 호스팅한다.
--   - rooms: 방 앵커(code PK, game, status). 한 방 = 한 게임(mafia/defense/subway).
--   - 플레이어/게임 상태는 모두 room_code 로 스코핑된다.
--   - 싱글톤이던 상태표(game_state, *_phase_state, stock_state, monster_count, rules_state)는
--     방 단위 PK 로 바뀐다.
--   - 방 생성 시 해당 방의 상태 행(시드)을 만든다(전역 시드 없음).
-- ============================================================================
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT USAGE, CREATE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 방 앵커
-- ============================================================================
CREATE TABLE rooms (
  code TEXT NOT NULL,
  game TEXT NOT NULL,                          -- 'mafia' | 'defense' | 'subway'
  status TEXT NOT NULL DEFAULT 'active',       -- 'active' | 'ended'
  ended_normally BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (code)
);

-- ============================================================================
-- 공통: 플레이어(방 단위), 방별 게임 상태/규칙
-- ============================================================================
CREATE TABLE players (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  room_code TEXT NOT NULL REFERENCES rooms(code),
  nickname TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  feather INTEGER DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (room_code, nickname)
);

-- 방별 단일 행(방=게임). active_game 은 방의 진행 상태('ready'|'mafia_tutorial'|'mafia'|'defense'|'subway' 등),
-- 타이머도 방 단위.
CREATE TABLE game_state (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  active_game TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  timer_start BOOLEAN,
  timer_start_at TIMESTAMPTZ,
  pause_at TIMESTAMPTZ,
  PRIMARY KEY (room_code)
);

CREATE TABLE rules_state (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  rule_key TEXT NOT NULL,
  is_open BOOLEAN DEFAULT false,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (room_code, rule_key)
);

CREATE TABLE gm_memos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT REFERENCES rooms(code),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

-- 방 단위 일반 투표(설문/지목 등)
CREATE TABLE player_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT REFERENCES rooms(code),
  voter_id UUID,
  topic TEXT,
  target_id UUID,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

-- ============================================================================
-- 2게임 — 자본주의 마피아 (방 단위)
-- ============================================================================
CREATE TABLE mafia_phase_state (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round_number INTEGER NOT NULL,
  phase TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (room_code)
);

CREATE TABLE mafia_stock_state (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  stock_key TEXT NOT NULL,
  price INTEGER NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (room_code, stock_key)
);

CREATE TABLE mafia_player_state (
  player_id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  cash INTEGER,
  is_mafia BOOLEAN DEFAULT false,
  job TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  stocks JSONB,
  PRIMARY KEY (player_id)
);

CREATE TABLE mafia_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  player_id UUID,
  round_number INTEGER NOT NULL,
  phase TEXT NOT NULL,
  action_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round_number INTEGER,
  voter_id UUID,
  target_id UUID,
  vote_count INTEGER,
  unit_price INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_player_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  player_id UUID,
  round_number INTEGER,
  phase TEXT,
  cash INTEGER,
  stocks JSONB,
  job TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_stock_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  stock_key TEXT,
  round_number INTEGER NOT NULL,
  price_before INTEGER,
  price_after INTEGER,
  meta JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_ability_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  player_id UUID,
  round_number INTEGER,
  phase TEXT,
  job TEXT,
  category TEXT,
  message TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_public_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round_number INTEGER,
  phase TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

-- ============================================================================
-- 3게임 — 디펜스 딜레마 (방 단위)
-- ============================================================================
CREATE TABLE defense_phase_state (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round BIGINT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (room_code)
);

CREATE TABLE defense_monster_count (
  room_code TEXT NOT NULL REFERENCES rooms(code),
  id INTEGER NOT NULL,                          -- 몬스터 종류 1~6
  count INTEGER NOT NULL,                        -- 진행 중 남은 풀(소모됨)
  base_count INTEGER NOT NULL,                   -- GM이 정하는 기준값(본게임 시작 시 count 가 이 값으로 리셋)
  PRIMARY KEY (room_code, id)
);

CREATE TABLE defense_score (
  player_id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  points INTEGER NOT NULL,
  PRIMARY KEY (player_id)
);

CREATE TABLE defense_score_snapshot (
  player_id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round INTEGER NOT NULL,
  points INTEGER NOT NULL,
  PRIMARY KEY (player_id, round)
);

CREATE TABLE defense_monster_instance (
  id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  monster_id INTEGER NOT NULL,
  current_hp INTEGER NOT NULL,
  remaining_time INTEGER NOT NULL,
  slot_index INTEGER NOT NULL,
  status TEXT NOT NULL,
  spawned_round INTEGER NOT NULL,
  removed_round INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE defense_monster_snapshot (
  instance_id UUID NOT NULL REFERENCES defense_monster_instance(id),
  room_code TEXT NOT NULL REFERENCES rooms(code),
  monster_id INTEGER NOT NULL,
  round INTEGER NOT NULL,
  current_hp INTEGER NOT NULL,
  remaining_time INTEGER NOT NULL,
  slot_index INTEGER NOT NULL,
  PRIMARY KEY (instance_id, round)
);

CREATE TABLE defense_card_state (
  player_id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  card_slot INTEGER NOT NULL,
  card_value INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL,
  PRIMARY KEY (player_id, card_slot)
);

CREATE TABLE defense_action (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  round INTEGER NOT NULL,
  player_id UUID NOT NULL,
  action_type TEXT NOT NULL,
  target_monster_id UUID,
  training_from INTEGER,
  training_to INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  rest_card TEXT,
  used_card_value BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE defense_player_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  player_id UUID NOT NULL,
  round INTEGER NOT NULL,
  log TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- ============================================================================
-- 1게임 — 이상교통(subway). 방 단위. (메인 분리 배포용; 라이브 1game-only 는 별도 DB)
-- ============================================================================
CREATE TABLE subway_player_state (
  player_id UUID NOT NULL,
  room_code TEXT NOT NULL REFERENCES rooms(code),
  exit_number INTEGER DEFAULT 0,
  current_location TEXT,
  reset_count INTEGER DEFAULT 0,
  is_finished BOOLEAN DEFAULT false,
  finished_rank INTEGER,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (player_id)
);

CREATE TABLE subway_player_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT REFERENCES rooms(code),
  player_id UUID,
  event_type TEXT NOT NULL,
  event_value JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE subway_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_code TEXT REFERENCES rooms(code),
  player_id UUID,
  reporter_name TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  decided_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

-- 이상교통 영구 기록(아카이브) — 방 종료 시점 보존
CREATE TABLE subway_play_records (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  room_code TEXT,
  session_id UUID NOT NULL,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  player_id UUID,
  nickname TEXT,
  final_exit INTEGER,
  reset_count INTEGER,
  is_finished BOOLEAN,
  finished_rank INTEGER,
  clear_seconds INTEGER,
  total_moves INTEGER,
  correct_moves INTEGER,
  wrong_moves INTEGER,
  forward_moves INTEGER,
  back_moves INTEGER,
  too_fast_count INTEGER,
  rules_discovered INTEGER,
  rules_discovered_ids INTEGER[],
  reports_submitted INTEGER,
  wrong_by_reason JSONB,
  wrong_by_group JSONB,
  visit_by_group JSONB,
  PRIMARY KEY (id)
);

-- ============================================================================
-- 외래키 (player_id → players)
-- ============================================================================
ALTER TABLE mafia_player_state      ADD CONSTRAINT fk_mafia_player_state_player_id      FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_actions           ADD CONSTRAINT fk_mafia_actions_player_id           FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_votes             ADD CONSTRAINT fk_mafia_votes_voter_id              FOREIGN KEY (voter_id) REFERENCES players(id);
ALTER TABLE mafia_votes             ADD CONSTRAINT fk_mafia_votes_target_id             FOREIGN KEY (target_id) REFERENCES players(id);
ALTER TABLE mafia_player_snapshots  ADD CONSTRAINT fk_mafia_player_snapshots_player_id  FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_stock_history     ADD CONSTRAINT fk_mafia_stock_history_stock_key     FOREIGN KEY (room_code, stock_key) REFERENCES mafia_stock_state(room_code, stock_key);
ALTER TABLE mafia_ability_results   ADD CONSTRAINT fk_mafia_ability_results_player_id   FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_score           ADD CONSTRAINT fk_defense_score_player_id           FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_score_snapshot  ADD CONSTRAINT fk_defense_score_snapshot_player_id  FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_card_state      ADD CONSTRAINT fk_defense_card_state_player_id      FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_action          ADD CONSTRAINT fk_defense_action_player_id          FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_player_log      ADD CONSTRAINT fk_defense_player_log_player_id      FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_player_state     ADD CONSTRAINT fk_subway_player_state_player_id     FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_player_events    ADD CONSTRAINT fk_subway_player_events_player_id    FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_reports          ADD CONSTRAINT fk_subway_reports_player_id          FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE player_votes            ADD CONSTRAINT fk_player_votes_voter_id             FOREIGN KEY (voter_id) REFERENCES players(id);
ALTER TABLE player_votes            ADD CONSTRAINT fk_player_votes_target_id            FOREIGN KEY (target_id) REFERENCES players(id);

-- ============================================================================
-- 인덱스 (방 단위 조회 가속)
-- ============================================================================
CREATE INDEX idx_players_room              ON players(room_code);
CREATE INDEX idx_mafia_actions_room        ON mafia_actions(room_code, round_number, phase);
CREATE INDEX idx_mafia_votes_room          ON mafia_votes(room_code, round_number);
CREATE INDEX idx_mafia_snapshots_room      ON mafia_player_snapshots(room_code, round_number);
CREATE INDEX idx_mafia_stock_history_room  ON mafia_stock_history(room_code, round_number);
CREATE INDEX idx_mafia_ability_room        ON mafia_ability_results(room_code, round_number);
CREATE INDEX idx_mafia_public_logs_room    ON mafia_public_logs(room_code);
CREATE INDEX idx_mafia_player_state_room   ON mafia_player_state(room_code);
CREATE INDEX idx_defense_monster_inst_room ON defense_monster_instance(room_code, status);
CREATE INDEX idx_defense_monster_snap_room ON defense_monster_snapshot(room_code, round);
CREATE INDEX idx_defense_action_room       ON defense_action(room_code, round);
CREATE INDEX idx_defense_player_log_room   ON defense_player_log(room_code, round);
CREATE INDEX idx_defense_score_room        ON defense_score(room_code);
CREATE INDEX idx_defense_score_snap_room   ON defense_score_snapshot(room_code, round);
CREATE INDEX idx_defense_card_state_room   ON defense_card_state(room_code);

-- 방 생성 시 해당 방의 상태 시드는 애플리케이션(POST /api/gm/rooms)에서 생성합니다.
-- (전역 시드 없음)
