-- ============================================================================
-- 부엉이게임 파일럿 — 새 DB 재초기화 스크립트
-- Supabase SQL Editor 에 전체 붙여넣고 Run. public 스키마를 비우고 재생성합니다.
-- ⚠️ 기존 데이터가 있으면 모두 삭제됩니다.
-- ============================================================================
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT USAGE, CREATE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE players (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  nickname TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  feather INTEGER DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE defense_monster_count (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  count INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE mafia_stock_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  stock_key TEXT,
  round_number INTEGER NOT NULL,
  price_before INTEGER,
  price_after INTEGER,
  meta JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_phase_state (
  id INTEGER NOT NULL DEFAULT 1,
  round_number INTEGER NOT NULL,
  phase TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_player_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID,
  round_number INTEGER,
  phase TEXT,
  cash INTEGER,
  stocks JSONB,
  job TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_score (
  player_id UUID NOT NULL,
  points INTEGER NOT NULL,
  PRIMARY KEY (player_id)
);

CREATE TABLE mafia_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID,
  round_number INTEGER NOT NULL,
  phase TEXT NOT NULL,
  action_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_monster_snapshot (
  instance_id UUID NOT NULL,
  monster_id INTEGER NOT NULL,
  round INTEGER NOT NULL,
  current_hp INTEGER NOT NULL,
  remaining_time INTEGER NOT NULL,
  slot_index INTEGER NOT NULL,
  PRIMARY KEY (instance_id, round)
);

CREATE TABLE gm_memos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE mafia_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  round_number INTEGER,
  voter_id UUID,
  target_id UUID,
  vote_count INTEGER,
  unit_price INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_player_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID NOT NULL,
  round INTEGER NOT NULL,
  log TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE subway_player_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID,
  event_type TEXT NOT NULL,
  event_value JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_score_snapshot (
  player_id UUID NOT NULL,
  round INTEGER NOT NULL,
  points INTEGER NOT NULL,
  PRIMARY KEY (player_id, round)
);

CREATE TABLE player_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  voter_id UUID,
  topic TEXT,
  target_id UUID,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_card_state (
  player_id UUID NOT NULL,
  card_slot INTEGER NOT NULL,
  card_value INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL,
  PRIMARY KEY (player_id, card_slot)
);

CREATE TABLE defense_phase_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  round BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE subway_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID,
  reporter_name TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  decided_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

CREATE TABLE subway_player_state (
  player_id UUID NOT NULL,
  exit_number INTEGER DEFAULT 0,
  current_location TEXT,
  reset_count INTEGER DEFAULT 0,
  is_finished BOOLEAN DEFAULT false,
  finished_rank INTEGER,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (player_id)
);

CREATE TABLE subway_play_records (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  player_id UUID,
  nickname TEXT,
  final_exit INTEGER,
  reset_count INTEGER,
  is_finished BOOLEAN,
  finished_rank INTEGER,
  clear_seconds INTEGER,
  total_moves INTEGER,
  correct_moves INTEGER,
  wrong_moves INTEGER,
  forward_moves INTEGER,
  back_moves INTEGER,
  too_fast_count INTEGER,
  rules_discovered INTEGER,
  rules_discovered_ids INTEGER[],
  reports_submitted INTEGER,
  wrong_by_reason JSONB,
  wrong_by_group JSONB,
  visit_by_group JSONB,
  PRIMARY KEY (id)
);

CREATE TABLE mafia_player_state (
  player_id UUID NOT NULL,
  cash INTEGER,
  is_mafia BOOLEAN DEFAULT false,
  job TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  stocks JSONB,
  PRIMARY KEY (player_id)
);

CREATE TABLE mafia_stock_state (
  stock_key TEXT NOT NULL,
  price INTEGER NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (stock_key)
);

CREATE TABLE mafia_ability_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  player_id UUID,
  round_number INTEGER,
  phase TEXT,
  job TEXT,
  category TEXT,
  message TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE game_state (
  id INTEGER NOT NULL DEFAULT 1,
  active_game TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  timer_start BOOLEAN,
  timer_start_at TIMESTAMPTZ,
  pause_at TIMESTAMPTZ,
  PRIMARY KEY (id)
);

CREATE TABLE rules_state (
  rule_key TEXT NOT NULL,
  is_open BOOLEAN DEFAULT false,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (rule_key)
);

CREATE TABLE mafia_public_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  round_number INTEGER,
  phase TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE defense_monster_instance (
  id UUID NOT NULL,
  monster_id INTEGER NOT NULL,
  current_hp INTEGER NOT NULL,
  remaining_time INTEGER NOT NULL,
  slot_index INTEGER NOT NULL,
  status TEXT NOT NULL,
  spawned_round INTEGER NOT NULL,
  removed_round INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE defense_action (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  round INTEGER NOT NULL,
  player_id UUID NOT NULL,
  action_type TEXT NOT NULL,
  target_monster_id UUID,
  training_from INTEGER,
  training_to INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  rest_card TEXT,
  used_card_value BIGINT,
  PRIMARY KEY (id)
);

-- 외래키
ALTER TABLE mafia_stock_history ADD CONSTRAINT fk_mafia_stock_history_stock_key FOREIGN KEY (stock_key) REFERENCES mafia_stock_state(stock_key);
ALTER TABLE mafia_player_snapshots ADD CONSTRAINT fk_mafia_player_snapshots_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_score ADD CONSTRAINT fk_defense_score_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_actions ADD CONSTRAINT fk_mafia_actions_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_monster_snapshot ADD CONSTRAINT fk_defense_monster_snapshot_instance_id FOREIGN KEY (instance_id) REFERENCES defense_monster_instance(id);
ALTER TABLE mafia_votes ADD CONSTRAINT fk_mafia_votes_voter_id FOREIGN KEY (voter_id) REFERENCES players(id);
ALTER TABLE mafia_votes ADD CONSTRAINT fk_mafia_votes_target_id FOREIGN KEY (target_id) REFERENCES players(id);
ALTER TABLE defense_player_log ADD CONSTRAINT fk_defense_player_log_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_player_events ADD CONSTRAINT fk_subway_player_events_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_score_snapshot ADD CONSTRAINT fk_defense_score_snapshot_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE player_votes ADD CONSTRAINT fk_player_votes_voter_id FOREIGN KEY (voter_id) REFERENCES players(id);
ALTER TABLE player_votes ADD CONSTRAINT fk_player_votes_target_id FOREIGN KEY (target_id) REFERENCES players(id);
ALTER TABLE defense_card_state ADD CONSTRAINT fk_defense_card_state_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_reports ADD CONSTRAINT fk_subway_reports_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE subway_player_state ADD CONSTRAINT fk_subway_player_state_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_player_state ADD CONSTRAINT fk_mafia_player_state_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE mafia_ability_results ADD CONSTRAINT fk_mafia_ability_results_player_id FOREIGN KEY (player_id) REFERENCES players(id);
ALTER TABLE defense_action ADD CONSTRAINT fk_defense_action_player_id FOREIGN KEY (player_id) REFERENCES players(id);

-- ============================================================================
-- 시드 데이터 (기존 DB 기준)
-- ============================================================================
INSERT INTO game_state (id, active_game, timer_start) VALUES (1, 'ready', false);

INSERT INTO rules_state (rule_key, is_open) VALUES
  ('intro', false), ('subway', false), ('mafia', false), ('defense', false);

INSERT INTO mafia_stock_state (stock_key, price) VALUES
  ('부엉교육', 5), ('번쩍전기', 5), ('국채', 5), ('이상교통', 5);

INSERT INTO mafia_phase_state (id, round_number, phase) VALUES (1, 0, 'prepare');

INSERT INTO defense_phase_state (id, round) VALUES (1, 0);

INSERT INTO defense_monster_count (id, count) VALUES
  (1, 6), (2, 4), (3, 5), (4, 4), (5, 3), (6, 2);
